version: "2"
# NOTE: golangci-lint v2 introduced schema changes. If CI uses the golangci-lint GitHub Action,
# ensure the action installs a v2 binary (golangci/golangci-lint-action@v8+ and `version: v2.x`)
# For local usage, `golangci-lint migrate` can help update older configs to v2.
run:
  timeout: 5m

linters:
  disable:
    - errcheck      # Disable error checking
    - gosec         # Disable security checks
    - staticcheck   # Disable static analysis
    - unused        # Disable unused variable checks
    - ineffassign   # Disable ineffective assignment checks
